export interface Day {
  year: string;
  quarter: number;
  month: string;
  week: number;
  week_day: number;
  is_today: boolean;
  day: string;
  ad: string;
  AD_date: {
    ad: string;
    bs: string;
    bs_day: number;
    bs_month: number;
    bs_year: number;
    tithi: number;
    ns_month: string;
    ns_year: number;
    chandrama: number;
    is_verified: number;
    remarks: string;
  };
  events: Event[];
}

export interface Event {
  ad: string;
  bs: string;
  bs_day: number;
  bs_month: number;
  bs_year: number;
  tithi: number;
  ns_month: string;
  ns_year: number;
  chandrama: number;
  is_verified: number;
  remarks: string;
  updated_at: string;
  event_index_id: number;
  event_date: string;
  ex_date: null | string;
  id: string;
  jpid: null | string;
  jtl: string;
  jds: {
    jnid: string;
    jct: string;
    ne: string;
    en: string;
    jiu: string;
    jis: string;
    jbi: string;
    jie: string;
    jbd: string;
    gh: string;
  };
  jsdt: string;
  jed: string;
  recurring_end_date: string;
  jir: number;
  has_reminder: number;
  status: number;
  duration: number;
  rrule: string;
  jci: string;
  jbo: string;
  jcb: string;
  jlo: string;
  jtp: null | string;
  priority: null | string;
  verification_id: null | string;
  event_verified_date: null | string;
  verification_status: null | string;
  verification_remarks: null | string;
  exception_date: null | string;
  new_date: null | string;
  exception_status: null | string;
  exception_remarks: null | string;
  holiday_date: null | string;
  holiday_type: null | string;
  holiday_status: null | string;
  gh: number;
  jfr: {
    jfrri: string;
    jfrm: string;
    jfrmd: string;
    jfrrt: string;
  };
  jeddt: [];
}
