export const np_nepaliMonths = [
  "बैशाख",
  "जेठ",
  "असार",
  "श्रावण",
  "भदौ",
  "आश्विन",
  "कार्तिक",
  "मंसिर",
  "पुष",
  "माघ",
  "फाल्गुन",
  "चैत्र",
];
export const en_nepaliMonths = [
  "Baisakh",
  "Jestha",
  "Ashad",
  "Shrawn",
  "Bhadra",
  "Ashoj",
  "Kartik",
  "Mangshir",
  "Paush",
  "Magh",
  "Falgun",
  "Chaitra",
];
export const nepaliMonths = [
  { en: "Baisakh", np: "बैशाख", ad: "Apr/May" },
  { en: "Jestha", np: "जेठ", ad: "May/Jun" },
  { en: "Ashad", np: "असार", ad: "Jun/Jul" },
  { en: "Shrawn", np: "श्रावण", ad: "Jul/Aug" },
  { en: "Bhadra", np: "भदौ", ad: "Aug/Sep" },
  { en: "Ashoj", np: "आश्विन", ad: "Sep/Oct" },
  { en: "Kartik", np: "कार्तिक", ad: "Oct/Nov" },
  { en: "Mangshir", np: "मंसिर", ad: "Nov/Dec" },
  { en: "Paush", np: "पुष", ad: "Dec/Jan" },
  { en: "Magh", np: "माघ", ad: "Jan/Febr" },
  { en: "Falgun", np: "फाल्गुन", ad: "Febr/Mar" },
  { en: "Chaitra", np: "चैत्र", ad: "Mar/Apr" },
];
